class Sale {
    static _repository = new SaleRepository();
    
    static _sanitize(data) {
        if (!data) return data;
        const numericFields = [
            'total', 'subtotal', 'tax', 'paidAmount', 'base_amount', 
            'tax_amount', 'commission_amount', 'customerId', 'saleNumber', 
            'cashRegisterId', 'userId', 'updatedBy'
        ];
        const intFields = ['id', 'saleNumber', 'customerId', 'cashRegisterId', 'userId', 'updatedBy'];
        intFields.forEach(field => {
            if (data[field] !== undefined && data[field] !== null && data[field] !== '') {
                const n = parseInt(data[field], 10);
                if (!isNaN(n)) data[field] = n;
            }
        });
        numericFields.forEach(field => {
            if (intFields.includes(field)) return;
            if (data[field] !== undefined && data[field] !== null) {
                data[field] = parseFloat(data[field]) || 0;
            }
        });
        return data;
    }

    /**
     * Modelo IVA 19% + Comisión 40% (Chile/Notebook style)
     * total = final_price; 
     * price_with_tax = total / 1.40; 
     * base = Math.round(price_with_tax / 1.19); 
     * tax = price_with_tax - base; 
     * commission = total - price_with_tax.
     * @param {number} total 
     * @param {string} documentType - 'boleta' o 'sin_boleta'
     */
    static computeFiscalFromTotal(total, documentType = 'boleta') {
        const TAX_RATE = 0.19;
        const COMMISSION_RATE = 0.40;

        // Si no es boleta, no hay IVA para este reporte
        if (documentType !== 'boleta') {
            return {
                base_amount: total,
                tax_amount: 0,
                commission_amount: Math.round(total - (total / (1 + COMMISSION_RATE))),
                tax_rate: 0,
                commission_rate: COMMISSION_RATE,
                price_with_tax: total
            };
        }

        // Formula Legal Chile (Boletas)
        // IVA = Total - Redondeo(Total / 1.19)
        const baseAmount = Math.round(total / (1 + TAX_RATE));
        const taxAmount = total - baseAmount;

        // Comisión interna (Profit sugerido 40% margin)
        const commissionAmount = Math.round(total - (total / (1 + COMMISSION_RATE)));

        return {
            base_amount: baseAmount, // Neto legal
            tax_amount: taxAmount,   // IVA Débito legal (19%)
            commission_amount: commissionAmount, // Profit interno
            tax_rate: TAX_RATE,
            commission_rate: COMMISSION_RATE,
            price_with_tax: total // Legalmente todo el monto es la venta afecta
        };
    }

    /**
     * Create sale record (internal method - use SaleService.createSale() instead)
     * CRITICAL: Always inserts as NEW row, never uses INSERT OR REPLACE
     * ID is auto-generated by IndexedDB auto-increment
     * 
     * @param {Object} sale - Sale object (MUST NOT include id field)
     * @returns {Promise<number>} - Auto-generated Sale ID
     */
    static async createSaleRecord(sale) {
        // CRITICAL: Ensure sale object does NOT have id field
        // BaseRepository.create() will remove it, but we ensure it here too
        if (sale.id !== undefined) {
            console.warn('⚠️ Warning: Attempted to create sale with explicit id. ID removed - will use auto-increment.');
            delete sale.id;
        }

        // CRITICAL: Use repository.create() which uses db.add()
        // db.add() ALWAYS inserts as new row (never replaces)
        // Auto-increment ensures unique ID generation (never reused)
        return await this._repository.create(sale);
    }

    /**
     * Create sale using SaleService (recommended)
     * @param {Object} data - Sale data (may include idempotencyKey for idempotency)
     * @returns {Promise<number|{saleId: number, fromIdempotency: boolean}>} - Sale ID or { saleId, fromIdempotency: true } when duplicate avoided
     */
    static async create(data) {
        return await SaleService.createSale(data);
    }

    /**
     * Find sale by idempotency key (optional field on sale).
     * @param {string} key - Idempotency key
     * @returns {Promise<Object|null>}
     */
    static async findByIdempotencyKey(key) {
        return await this._repository.findByIdempotencyKey(key);
    }

    static async getById(id) {
        return await this._repository.findById(id);
    }

    static async getAll() {
        return await this._repository.findAll();
    }

    static async getLastSale() {
        return await this._repository.findLast();
    }

    static async getByDateRange(startDate, endDate, params = {}) {
        return await this._repository.findByDateRange(startDate, endDate, params);
    }

    /**
     * Get latest sales with pagination
     */
    static async getLatest(limit = 50, offset = 0) {
        return await this._repository.findLatest(limit, offset);
    }

    /**
     * Get statistical summary of sales
     */
    static async getStatsSummary() {
        if (db.mode === 'sqlite') {
            return await window.ApiClient.get('sales/stats/summary');
        }
        return null;
    }

    static async getByCustomer(customerId, params = {}) {
        return await this._repository.findByCustomerId(customerId, params);
    }

    static async getByCashRegister(cashRegisterId) {
        return await this._repository.findByCashRegisterId(cashRegisterId);
    }

    static async getTodaySales() {
        return await this._repository.findToday();
    }

    static async getTotalByPaymentMethod(cashRegisterId) {
        return await this._repository.getTotalByPaymentMethod(cashRegisterId);
    }

    static async getPendingSales(params = {}) {
        return await this._repository.findPending(params);
    }

    static async count() {
        return await this._repository.count();
    }

    /**
     * Register payment (IMMUTABLE - creates new object instead of mutating)
     * @param {number} saleId - Sale ID
     * @param {number} amount - Payment amount
     * @returns {Promise<Object>} - Updated sale
     */
    static async registerPayment(saleId, amount) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        // Verify we're updating the correct sale
        if (sale.id !== saleId) {
            throw new Error('Error: ID de venta no coincide');
        }

        const paymentAmount = parseFloat(amount) || 0;
        if (paymentAmount <= 0) {
            throw new Error('El monto del pago debe ser mayor a 0');
        }

        const originalPaidAmount = parseFloat(sale.paidAmount) || 0;
        const originalTotal = parseFloat(sale.total) || 0;
        const originalRemaining = originalTotal - originalPaidAmount;

        // Verify we're not trying to pay more than what's remaining
        if (paymentAmount > originalRemaining) {
            console.warn('Payment amount exceeds remaining debt. Adjusting...', {
                saleId,
                paymentAmount,
                originalRemaining
            });
            const adjustedAmount = Math.min(paymentAmount, originalRemaining);
            if (adjustedAmount <= 0) {
                throw new Error('La venta ya está completamente pagada');
            }
            // Continue with adjusted amount
        }

        // Calculate new paid amount (IMMUTABLE - create new values)
        const newPaidAmount = Math.min(originalPaidAmount + paymentAmount, originalTotal);
        const isFullyPaid = newPaidAmount >= originalTotal;
        const hasPartialPayment = newPaidAmount > 0 && newPaidAmount < originalTotal;

        // Determine status: paid (completed), partial, or pending
        let newStatus = sale.status;
        if (isFullyPaid) {
            newStatus = 'completed'; // Fully paid
        } else if (hasPartialPayment) {
            newStatus = 'partial'; // Partially paid
        } else {
            newStatus = 'pending'; // No payment yet
        }

        // Create updated sale object (IMMUTABLE)
        const updated = this._sanitize({
            ...sale,
            paidAmount: isFullyPaid ? originalTotal : newPaidAmount,
            status: newStatus,
            paidAt: isFullyPaid ? new Date().toISOString() : null,
            updatedAt: new Date().toISOString()
        });

        // Replace sale using repository
        await this._repository.replace(updated);

        // Verify the update worked correctly
        const verifiedSale = await this.getById(saleId);
        if (!verifiedSale) {
            throw new Error('Error: No se pudo verificar la actualización de la venta');
        }

        const expectedPaidAmount = Math.min(originalPaidAmount + paymentAmount, originalTotal);
        if (Math.abs(verifiedSale.paidAmount - expectedPaidAmount) > 0.01) {
            console.error('Payment update mismatch!', {
                saleId,
                originalPaidAmount,
                paymentAmount,
                expectedPaidAmount,
                actualPaidAmount: verifiedSale.paidAmount,
                originalTotal
            });
            throw new Error(`Error: El monto pagado no se actualizó correctamente. Esperado: ${expectedPaidAmount}, Actual: ${verifiedSale.paidAmount}`);
        }

        return verifiedSale;
    }

    /**
     * Update payment method (IMMUTABLE)
     * @param {number} saleId - Sale ID
     * @param {string} newMethod - New payment method
     * @returns {Promise<Object>} - Updated sale
     */
    static async updatePaymentMethod(saleId, newMethod) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        // Create updated sale object (IMMUTABLE)
        const updated = this._sanitize({
            ...sale,
            paymentMethod: newMethod,
            paymentDetails: null // Reset mixed payment details
        });

        await this._repository.replace(updated);
        return await this.getById(saleId);
    }

    /**
     * Update customer ID (helper method)
     * @param {number} saleId - Sale ID
     * @param {number} customerId - Customer ID
     * @returns {Promise<void>}
     */
    static async updateCustomerId(saleId, customerId) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        const updated = this._sanitize({
            ...sale,
            customerId: parseFloat(customerId) || 0
        });

        await this._repository.replace(updated);
    }

    /**
     * Update status (helper method)
     * @param {number} saleId - Sale ID
     * @param {string} status - New status
     * @returns {Promise<void>}
     */
    static async updateStatus(saleId, status) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        const updated = this._sanitize({
            ...sale,
            status: status
        });

        await this._repository.replace(updated);
    }

    static async getAccountsReceivable() {
        return await AccountService.getAccountsReceivable();
    }

    /**
     * Update sale items and recalculate totals
     * @param {number} saleId - Sale ID
     * @param {Array} newItems - New items array
     * @returns {Promise<Object>} - Updated sale
     */
    static async updateItems(saleId, newItems) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        // Calculate new totals
        const subtotal = newItems.reduce((sum, item) => sum + (parseFloat(item.total) || 0), 0);
        const total = roundPrice(subtotal);

        // Recalculate paidAmount if needed (for credit sales)
        const paidAmount = sale.paidAmount || 0;
        const newPaidAmount = sale.status === 'completed' ? total : Math.min(paidAmount, total);

        // Update status if needed
        let newStatus = sale.status;
        if (sale.status === 'completed' && newPaidAmount < total) {
            newStatus = newPaidAmount > 0 ? 'partial' : 'pending';
        } else if ((sale.status === 'pending' || sale.status === 'partial') && newPaidAmount >= total) {
            newStatus = 'completed';
        }

        const updated = this._sanitize({
            ...sale,
            items: newItems,
            subtotal: subtotal,
            total: total,
            paidAmount: newPaidAmount,
            status: newStatus
        });

        await this._repository.replace(updated);
        return await this.getById(saleId);
    }

    /**
     * Update sale with new data (items, payment method, etc.)
     * @param {number} saleId - Sale ID
     * @param {Object} updateData - Data to update
     * @returns {Promise<Object>} - Updated sale
     */
    static async updateSale(saleId, updateData) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        // ===== B3 FIX: Edición de venta con prevalidación y transacción atómica =====
        let stockOps = [];
        if (updateData.items && Array.isArray(updateData.items)) {
            const alreadyReturned = await SaleReturn.getReturnedQuantitiesBySale(saleId);

            const oldItems = sale.items || [];
            const newItems = updateData.items;
            const oldByProduct = {};
            oldItems.forEach(item => {
                const pid = Number(item.productId);
                if (!oldByProduct[pid]) oldByProduct[pid] = 0;
                oldByProduct[pid] += parseFloat(item.quantity) || 0;
            });
            const newByProduct = {};
            newItems.forEach(item => {
                const pid = Number(item.productId);
                if (!newByProduct[pid]) newByProduct[pid] = 0;
                newByProduct[pid] += parseFloat(item.quantity) || 0;
            });
            const oldProductIds = new Set(Object.keys(oldByProduct).map(Number).filter(n => !isNaN(n)));
            const newProductIds = new Set(Object.keys(newByProduct).map(Number).filter(n => !isNaN(n)));

            // Calcular todas las operaciones de stock necesarias ANTES de ejecutar
            // 1) Productos eliminados → restaurar
            for (const productId of oldProductIds) {
                if (!newProductIds.has(productId)) {
                    const qty = oldByProduct[productId] || 0;
                    if (qty > 0) stockOps.push({ action: 'restore', productId, qty });
                }
            }
            // 2) Productos en ambos → delta
            for (const productId of oldProductIds) {
                if (!newProductIds.has(productId)) continue;
                const delta = (newByProduct[productId] || 0) - (oldByProduct[productId] || 0);
                if (delta < 0) {
                    stockOps.push({ action: 'restore', productId, qty: Math.abs(delta) });
                } else if (delta > 0) {
                    stockOps.push({ action: 'deduct', productId, qty: delta });
                }
            }
            // 3) Productos nuevos → descontar
            for (const productId of newProductIds) {
                if (!oldProductIds.has(productId)) {
                    const qty = newByProduct[productId] || 0;
                    if (qty > 0) stockOps.push({ action: 'deduct', productId, qty });
                }
            }

            // PREVALIDACIÓN: verificar stock suficiente para TODAS las operaciones de descuento y cantidades devueltas
            for (const productId of newProductIds) {
                const newQty = newByProduct[productId] || 0;
                const returnedQty = alreadyReturned[productId] || 0;
                if (newQty < returnedQty && newQty >= 0) {
                    throw new Error(`El producto ID #${productId} ya tiene ${returnedQty} unidades devueltas. No puedes reducir la cantidad vendida a menos de eso.`);
                }
            }

            for (const op of stockOps) {
                if (op.action !== 'deduct') continue;
                const product = await Product.getById(op.productId);
                const validation = ProductValidator.validateStock(product, op.qty);
                if (!validation.valid) throw new Error(validation.error);
            }
        }

        // Recalcular totales, paidAmount y status consistentemente
        const itemsChanged = updateData.items && Array.isArray(updateData.items);
        if (itemsChanged) {
            const subtotal = updateData.items.reduce((sum, item) => sum + (parseFloat(item.total) || 0), 0);
            const total = roundPrice(subtotal);
            updateData.subtotal = subtotal;
            updateData.total = total;
        }

        const finalTotal = parseFloat(updateData.total !== undefined ? updateData.total : sale.total) || 0;

        if (updateData.paidAmount !== undefined) {
            updateData.paidAmount = Math.min(parseFloat(updateData.paidAmount) || 0, finalTotal);
        } else if (itemsChanged) {
            const currentPaidAmount = parseFloat(sale.paidAmount) || 0;
            updateData.paidAmount = sale.status === 'completed' ? finalTotal : Math.min(currentPaidAmount, finalTotal);
        }

        const finalPaid = parseFloat(updateData.paidAmount !== undefined ? updateData.paidAmount : sale.paidAmount) || 0;
        if (updateData.paidAmount !== undefined || itemsChanged) {
            if (finalPaid >= finalTotal && finalTotal > 0) {
                updateData.status = 'completed';
                updateData.paidAt = new Date().toISOString();
            } else if (finalPaid > 0) {
                updateData.status = 'partial';
                updateData.paidAt = null;
            } else {
                updateData.status = 'pending';
                updateData.paidAt = null;
            }
        }

        const singleMethods = ['cash', 'card', 'qr', 'other'];
        if (updateData.paymentMethod && singleMethods.includes(updateData.paymentMethod) && !('paymentDetails' in updateData)) {
            updateData.paymentDetails = null;
        }

        // Limpieza de tipos de datos para evitar SQLITE_MISMATCH
        const cleanData = { ...updateData };
        const numericFields = [
            'total', 'subtotal', 'tax', 'paidAmount', 'base_amount', 
            'tax_amount', 'commission_amount', 'customerId', 'saleNumber', 
            'cashRegisterId', 'userId', 'updatedBy'
        ];
        
        numericFields.forEach(field => {
            if (cleanData[field] !== undefined && cleanData[field] !== null) {
                cleanData[field] = parseFloat(cleanData[field]) || 0;
            }
            if (sale[field] !== undefined && sale[field] !== null) {
                sale[field] = parseFloat(sale[field]) || 0;
            }
        });

        const updated = this._sanitize({
            ...sale,
            ...cleanData,
            updatedAt: new Date().toISOString(),
            updatedBy: AuditLogService.getCurrentUserId()
        });

        // Ensure paidAmount is never higher than total (double check)
        if (updated.paidAmount > updated.total) {
            updated.paidAmount = updated.total;
        }

        // CRITICAL FIX: If there are stock operations, execute ALL changes
        // (stock + movements + sale update) in a SINGLE atomic transaction.
        // If any fails, everything rolls back - no orphan movements, no partial state.
        // B5: Si estamos en modo SQLite, usamos la API compleja del backend
        if (db.mode === 'sqlite') {
            try {
                // Notar que items y paymentChange deben venir en updateData si hay cambios
                const payload = {
                    saleData: { ...updated },
                    items: updateData.items || sale.items,
                    paymentChange: updateData.paymentChange || { diff: 0 }
                };
                // Limpiar campos que no van en la tabla sales si es necesario
                delete payload.saleData.items;
                delete payload.saleData.paymentChange;

                const response = await ApiClient.put('complex/sale', saleId, payload);
                db.clearCache('sales');
                db.clearCache('customers');
                db.clearCache('products');
                db.clearCache('stockMovements');
                return response;
            } catch (error) {
                console.error('Error en updateSale (SQLite):', error);
                throw error;
            }
        }

        if (stockOps && stockOps.length > 0) {
            await new Promise((resolve, reject) => {
                const tx = db.db.transaction(['sales', 'products', 'stockMovements'], 'readwrite');

                tx.onerror = () => reject(new Error(`Error al editar venta: ${tx.error?.message || 'Error desconocido'}`));
                tx.onabort = () => reject(new Error('Edición de venta abortada: stock y venta no fueron modificados'));
                tx.oncomplete = () => resolve();

                const saleStore = tx.objectStore('sales');
                const productStore = tx.objectStore('products');
                const movementStore = tx.objectStore('stockMovements');

                // Update sale record within transaction
                saleStore.put(updated);

                // Process stock operations (read products WITHIN transaction)
                for (const op of stockOps) {
                    const getReq = productStore.get(op.productId);
                    getReq.onsuccess = () => {
                        const product = getReq.result;
                        if (!product) { tx.abort(); return; }

                        const currentStock = parseFloat(product.stock) || 0;
                        let newStock;
                        if (op.action === 'restore') {
                            newStock = currentStock + op.qty;
                        } else {
                            newStock = currentStock - op.qty;
                            if (newStock < 0) { tx.abort(); return; }
                        }

                        productStore.put({
                            ...product,
                            stock: newStock,
                            updatedAt: new Date().toISOString()
                        });

                        const movementQty = op.action === 'restore' ? op.qty : -op.qty;
                        movementStore.add({
                            productId: op.productId,
                            type: op.action === 'restore' ? 'adjustment' : 'sale',
                            quantity: movementQty,
                            reference: saleId,
                            date: new Date().toISOString(),
                            reason: op.action === 'restore'
                                ? `Devolución por edición de venta #${sale.saleNumber || saleId}`
                                : `Descuento por edición de venta #${sale.saleNumber || saleId}`,
                            cost_value: (product.cost || 0) * Math.abs(movementQty),
                            sale_value: (product.price || 0) * Math.abs(movementQty)
                        });
                    };
                }
            });
        } else {
            // No stock changes, just update the sale normally
            await this._repository.replace(updated);
        }

        // C2: Audit log (after successful transaction)
        const changedKeys = Object.keys(updateData).filter(k => k !== 'updatedAt');
        AuditLogService.log({
            entity: 'sale', entityId: saleId, action: 'update',
            summary: `Venta #${sale.saleNumber || saleId} editada (${changedKeys.join(', ')})`,
            metadata: {
                saleNumber: sale.saleNumber,
                changedFields: changedKeys,
                newTotal: updated.total,
                newStatus: updated.status,
                newPaidAmount: updated.paidAmount
            }
        });

        return await this.getById(saleId);
    }

    /**
     * Delete a sale and all associated payments.
     * CRITICAL FIX: Uses a single atomic IndexedDB transaction.
     * Stock restore + movement creation + payment deletion + sale deletion
     * all succeed or all fail together. No orphan movements or partial state.
     * @param {number} saleId - Sale ID
     * @returns {Promise<void>}
     */
    static async delete(saleId) {
        const sale = await this.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        const payments = await Payment.getBySale(saleId);
        const returns = await SaleReturn.getBySale(saleId);
        const alreadyReturned = await SaleReturn.getReturnedQuantitiesBySale(saleId);
        const items = (sale.items || []).filter(item => item && item.productId && parseFloat(item.quantity) > 0);

        if (db.mode === 'sqlite') {
            const result = await ApiClient.delete('complex/sale', saleId);
            db.clearCache('sales');
            db.clearCache('customers');
            db.clearCache('products');
            db.clearCache('stockMovements');
            db.clearCache('cashMovements');
            return result;
        }

        await new Promise((resolve, reject) => {
            if (!db.db) return reject(new Error('Base de datos no inicializada'));
            const tx = db.db.transaction(['sales', 'products', 'stockMovements', 'payments', 'saleReturns', 'cashMovements'], 'readwrite');

            tx.onerror = () => reject(new Error(`Error al eliminar venta: ${tx.error?.message || 'Error desconocido'}`));
            tx.onabort = () => reject(new Error('Eliminación abortada: todos los cambios fueron revertidos'));
            tx.oncomplete = () => resolve();

            const saleStore = tx.objectStore('sales');
            const productStore = tx.objectStore('products');
            const movementStore = tx.objectStore('stockMovements');
            const paymentStore = tx.objectStore('payments');
            const returnStore = tx.objectStore('saleReturns');
            const cashMovementStore = tx.objectStore('cashMovements');

            // Restore stock for each item (read product WITHIN transaction)
            for (const item of items) {
                const originalQty = parseFloat(item.quantity);
                const returnedQty = alreadyReturned[item.productId] || 0;
                const qtyToRestore = originalQty - returnedQty;

                if (qtyToRestore <= 0) continue; // Ya fue devuelto todo en esta venta

                const getReq = productStore.get(item.productId);
                getReq.onsuccess = () => {
                    const product = getReq.result;
                    if (!product) return;
                    const currentStock = parseFloat(product.stock) || 0;
                    productStore.put({
                        ...product,
                        stock: currentStock + qtyToRestore,
                        updatedAt: new Date().toISOString()
                    });
                    movementStore.add({
                        productId: item.productId,
                        type: 'adjustment',
                        quantity: qtyToRestore,
                        reference: saleId,
                        date: new Date().toISOString(),
                        reason: `Devolución por eliminación de venta #${sale.saleNumber || saleId}`,
                        cost_value: (product.cost || 0) * qtyToRestore,
                        sale_value: (product.price || 0) * qtyToRestore
                    });
                };
            }

            // Delete payments AND associated cash movements
            // Use a counter to track when all async operations complete
            let paymentsProcessed = 0;
            const totalPayments = payments.length;
            
            const deletePaymentAndMovements = (paymentIndex) => {
                if (paymentIndex >= totalPayments) {
                    // All payments processed, proceed to delete returns and sale
                    deleteReturnsAndSale();
                    return;
                }
                
                const payment = payments[paymentIndex];
                const cashMovementIndex = cashMovementStore.index('paymentId');
                
                if (cashMovementIndex) {
                    const cashMovementRequest = cashMovementIndex.getAll(payment.id);
                    cashMovementRequest.onsuccess = () => {
                        const cashMovements = cashMovementRequest.result || [];
                        let movementsDeleted = 0;
                        
                        if (cashMovements.length === 0) {
                            // No movements to delete, delete payment and move to next
                            paymentStore.delete(payment.id);
                            deletePaymentAndMovements(paymentIndex + 1);
                            return;
                        }
                        
                        // Delete each cash movement
                        cashMovements.forEach(cm => {
                            const deleteReq = cashMovementStore.delete(cm.id);
                            deleteReq.onsuccess = () => {
                                movementsDeleted++;
                                if (movementsDeleted === cashMovements.length) {
                                    // All movements deleted, now delete payment
                                    paymentStore.delete(payment.id);
                                    deletePaymentAndMovements(paymentIndex + 1);
                                }
                            };
                            deleteReq.onerror = () => {
                                // Continue even if deletion fails
                                movementsDeleted++;
                                if (movementsDeleted === cashMovements.length) {
                                    paymentStore.delete(payment.id);
                                    deletePaymentAndMovements(paymentIndex + 1);
                                }
                            };
                        });
                    };
                    cashMovementRequest.onerror = () => {
                        // If index lookup fails, just delete payment and continue
                        paymentStore.delete(payment.id);
                        deletePaymentAndMovements(paymentIndex + 1);
                    };
                } else {
                    // No index exists, just delete payment
                    paymentStore.delete(payment.id);
                    deletePaymentAndMovements(paymentIndex + 1);
                }
            };
            
            const deleteReturnsAndSale = () => {
                // Delete returns
                for (const ret of returns) {
                    returnStore.delete(ret.id);
                }
                
                // Delete sale
                saleStore.delete(saleId);
            };
            
            // Start deleting payments
            if (totalPayments === 0) {
                deleteReturnsAndSale();
            } else {
                deletePaymentAndMovements(0);
            }
        });

        // C2: Audit log (after successful atomic transaction)
        AuditLogService.log({
            entity: 'sale', entityId: saleId, action: 'delete',
            summary: `Venta #${sale.saleNumber || saleId} eliminada — stock restaurado`,
            metadata: {
                saleNumber: sale.saleNumber,
                total: sale.total,
                itemCount: items.length,
                paymentsDeleted: payments.length
            }
        });
    }
}

