/**
 * Sale Service
 * Centralizes sale creation and business logic
 */
class SaleService {
    /**
     * Generate next sale number (consecutivo).
     * Usa MAX(saleNumber) en SQLite para evitar findAll() lento y corrupción por concatenación.
     */
    static async generateSaleNumber() {
        let max = 0;
        if (db.mode === 'sqlite') {
            try {
                const res = await window.ApiClient.get('sales/max-sale-number');
                // Aseguramos que max sea un número real antes de sumar
                max = (res && typeof res.max !== 'undefined') ? (parseInt(res.max, 10) || 0) : 0;
                return max + 1;
            } catch (e) {
                console.warn('generateSaleNumber fallback due to API failure:', e);
            }
        }

        // Fallback or IndexedDB
        try {
            const lastSale = await Sale.getLastSale();
            const lastNum = lastSale && lastSale.saleNumber != null ? parseInt(lastSale.saleNumber, 10) : 0;
            max = isNaN(lastNum) ? 0 : lastNum;
            return max + 1;
        } catch (e) {
            console.error('Error total generando numero de venta:', e);
            return 1;
        }
    }

    /**
     * Validate sale data before creation (uses SaleValidator)
     * @param {Object} saleData - Sale data
     * @returns {Object} - { valid: boolean, error?: string }
     */
    static validateSaleData(saleData) {
        return SaleValidator.validate(saleData);
    }

    /**
     * Create a sale with all business logic
     * @param {Object} saleData - Sale data
     * @returns {Promise<number>} - Sale ID
     */
    static async createSale(saleData) {
        // Idempotency: if key present and sale already exists, return existing (no new sale, no stock deduction)
        const idempotencyKey = saleData.idempotencyKey != null && String(saleData.idempotencyKey).trim() !== ''
            ? String(saleData.idempotencyKey).trim()
            : null;
        if (idempotencyKey) {
            const existing = await Sale.findByIdempotencyKey(idempotencyKey);
            if (existing) {
                return { saleId: existing.id, fromIdempotency: true };
            }
        }

        // Validate sale data
        const validation = this.validateSaleData(saleData);
        if (!validation.valid) {
            throw new Error(validation.error);
        }

        // Generate sale number
        const saleNumber = parseInt(await this.generateSaleNumber(), 10) || 1;

        // Ensure customerId is set for pending sales
        const isPending = saleData.status === 'pending' || saleData.status === 'partial';

        // CRITICAL: Credit sales MUST have customerId - validate this
        if (isPending && !saleData.customerId) {
            throw new Error('Las ventas a crédito (fiadas) deben tener un cliente asociado');
        }

        // Límite de crédito: si el cliente tiene límite, deuda actual + total de esta venta no puede superarlo
        if (isPending && saleData.customerId) {
            const customer = await Customer.getById(saleData.customerId);
            if (customer && customer.creditLimit != null && !isNaN(parseFloat(customer.creditLimit))) {
                const limit = parseFloat(customer.creditLimit);
                const balance = await AccountService.getCustomerBalance(saleData.customerId);
                const newTotalDebt = (balance.totalDebt || 0) + (parseFloat(saleData.total) || 0);
                if (newTotalDebt > limit) {
                    throw new Error(
                        `Límite de crédito superado. Deuda actual: ${formatCLP(balance.totalDebt || 0)}, ` +
                        `esta venta: ${formatCLP(saleData.total)}, total: ${formatCLP(newTotalDebt)}. Límite del cliente: ${formatCLP(limit)}.`
                    );
                }
            }
        }

        // CRITICAL: Build sale object WITHOUT id field
        // ID will be auto-generated by IndexedDB auto-increment
        // This ensures each sale is a NEW unique record
        const sale = {
            saleNumber: saleNumber,
            date: new Date().toISOString(),
            // CRITICAL: For credit sales, customerId MUST be set (never null)
            // For completed sales, customerId can be null (walk-in customers)
            customerId: isPending ? saleData.customerId : (saleData.customerId || null),
            items: Array.isArray(saleData.items) ? saleData.items : [],
            subtotal: parseFloat(saleData.subtotal) || 0,
            total: parseFloat(saleData.total) || 0,
            paymentMethod: saleData.paymentMethod || 'cash',
            paymentDetails: saleData.paymentDetails || null,
            cashRegisterId: saleData.cashRegisterId,
            status: saleData.status || 'completed',
            paidAmount: saleData.paidAmount !== undefined && !isNaN(parseFloat(saleData.paidAmount)) ? parseFloat(saleData.paidAmount) : (isPending ? 0 : parseFloat(saleData.total) || 0),

            // Notebook Features: Desglose Fiscal
            ...Sale.computeFiscalFromTotal(parseFloat(saleData.total) || 0),

            // B6: Campos de auditoría
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            // C3: Trazabilidad — quién creó/modificó
            createdBy: AuditLogService.getCurrentUserId(),
            updatedBy: AuditLogService.getCurrentUserId()
        };
        if (idempotencyKey) {
            sale.idempotencyKey = idempotencyKey;
        }

        // CRITICAL: Ensure sale object does NOT have id field
        if (sale.id !== undefined) {
            delete sale.id;
        }

        // Stock negativo permitido por diseño del negocio — solo validamos que el producto exista
        const validItems = [];
        for (const item of sale.items) {
            if (!item || !item.productId || item.quantity === undefined) continue;
            const qty = parseFloat(item.quantity) || 0;
            if (qty <= 0) continue;
            const product = await Product.getById(item.productId);
            if (!product) throw new Error(`Producto ${item.productId} no encontrado`);
            validItems.push({ productId: item.productId, qty, price: item.unitPrice });
        }

        // CRITICAL FIX: Single atomic transaction - sale + product updates + stock movements
        let saleId;
        let fromIdempotency = false;
        if (db.mode === 'sqlite') {
            const result = await ApiClient.post('complex/sale', { sale, validItems });
            if (!result.success) throw new Error(result.error || 'Error al crear venta en SQLite');
            saleId = result.id;
            fromIdempotency = result.fromIdempotency === true;
            // CRITICAL: Clear cache to ensure immediate synchronization of debt/stock
            db.clearCache('sales');
            db.clearCache('customers');
            db.clearCache('products');
            db.clearCache('stockMovements');
        } else {
            // Original IndexedDB Transaction
            saleId = await new Promise((resolve, reject) => {
                const tx = db.db.transaction(['sales', 'products', 'stockMovements'], 'readwrite');
                let resolvedSaleId = null;

                tx.onerror = () => {
                    reject(new Error(`Transacción fallida: ${tx.error?.message || 'Error desconocido'}`));
                };
                tx.onabort = () => {
                    reject(new Error('Transacción abortada: venta y stock se revirtieron'));
                };
                tx.oncomplete = () => {
                    resolve(resolvedSaleId);
                };

                const saleStore = tx.objectStore('sales');
                const productStore = tx.objectStore('products');
                const movementStore = tx.objectStore('stockMovements');

                const saleRequest = saleStore.add(sale);
                saleRequest.onsuccess = async () => {
                    const id = saleRequest.result;
                    if (!id || typeof id !== 'number') {
                        tx.abort();
                        return;
                    }
                    resolvedSaleId = id;

                    try {
                        for (const { productId, qty } of validItems) {
                            // Usar el motor central PASANDO LA TRANSACCIÓN ACTUAL (tx)
                            await StockService.applyStockMovement(productId, -qty, 'sale', id, '', tx);
                        }
                    } catch (err) {
                        console.error('Error applying stock during sale:', err);
                        tx.abort();
                    }
                };
                saleRequest.onerror = () => {
                    tx.abort();
                };
            });
        }

        // C2: Audit log (después de la transacción atómica exitosa)
        if (!fromIdempotency) {
            AuditLogService.log({
                entity: 'sale', entityId: saleId, action: 'create',
                summary: `Venta #${saleNumber} creada — Total: ${sale.total}, Estado: ${sale.status}`,
                metadata: {
                    saleNumber,
                    total: sale.total,
                    status: sale.status,
                    paymentMethod: sale.paymentMethod,
                    customerId: sale.customerId,
                    itemCount: sale.items.length
                }
            });
        }

        if (fromIdempotency) return { saleId, fromIdempotency: true };
        return saleId;
    }

    /**
     * Calculate paid amount from payment details
     * @param {Object|null} paymentDetails - Payment details object
     * @param {number} defaultAmount - Default amount if no payment details
     * @returns {number}
     */
    static calculatePaidAmount(paymentDetails, defaultAmount = 0) {
        if (!paymentDetails) {
            return defaultAmount;
        }

        return Object.values(paymentDetails).reduce((sum, val) => sum + (parseFloat(val) || 0), 0);
    }

    /**
     * Delete a sale and restore stock
     */
    static async deleteSale(saleId) {
        const sale = await Sale.getById(saleId);
        if (!sale) throw new Error('Venta no encontrada');

        // Restore stock in an atomic transaction
        if (db.mode === 'sqlite') {
            const result = await ApiClient.delete(`complex/sale/${saleId}`);
            if (!result.success) throw new Error(result.error || 'Error al anular venta en SQLite');
            // Log auditing (after successful transaction)
            AuditLogService.log({
                entity: 'sale', entityId: saleId, action: 'delete',
                summary: `Venta #${sale.saleNumber} eliminada (SQLite). Stock devuelto.`,
                metadata: { total: sale.total, customerId: sale.customerId }
            });
            // CRITICAL: Clear cache to ensure immediate synchronization of debt/stock
            if (db.clearCache) {
                db.clearCache('sales');
                db.clearCache('customers');
                db.clearCache('products');
                db.clearCache('stockMovements');
            }
            return true;
        }

        return new Promise((resolve, reject) => {
            const tx = db.db.transaction(['sales', 'products', 'stockMovements'], 'readwrite');

            tx.onerror = () => reject(new Error(`Error al anular venta: ${tx.error?.message}`));
            tx.oncomplete = () => {
                // Log auditing (after successful transaction)
                AuditLogService.log({
                    entity: 'sale', entityId: saleId, action: 'delete',
                    summary: `Venta #${sale.saleNumber} eliminada (Transacción Atómica). Stock devuelto.`,
                    metadata: { total: sale.total, customerId: sale.customerId }
                });
                resolve(true);
            };

            const saleStore = tx.objectStore('sales');
            const productStore = tx.objectStore('products');
            const movementStore = tx.objectStore('stockMovements');

            // 1. Marcar como eliminada o borrar
            saleStore.delete(saleId);

            // 2. Devolver stock e historial
            for (const item of sale.items) {
                if (!item.productId) continue;

                const getReq = productStore.get(item.productId);
                getReq.onsuccess = () => {
                    const product = getReq.result;
                    if (product) {
                        const qty = parseFloat(item.quantity) || 0;
                        const newStock = Math.round(((parseFloat(product.stock) || 0) + qty) * 100) / 100;

                        productStore.put({
                            ...product,
                            stock: newStock,
                            updatedAt: new Date().toISOString()
                        });

                        movementStore.add({
                            productId: product.id,
                            type: 'adjustment',
                            quantity: qty,
                            reference: saleId,
                            date: new Date().toISOString(),
                            reason: `Anulación Venta #${sale.saleNumber}`
                        });
                    }
                };
            }
        });
    }
}
